# tomcat
server:
  port: 8003

# eureka
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka/

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# spring
spring:
  application:
    name: service-product

  # database
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
  profiles:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 1

  # rabbitmq
  rabbitmq:
    host: 101.200.225.183
    port: 5672
    username: test
    password: 123456

# mybatis-plus
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
    call-setters-on-nulls: true
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: ai.ssy.*.*.model
  global-config:
    db-config:
      id-type: id_worker
      field-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
    sql-parser-cache: true
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    cache-enabled: false

